version: v2beta1
name: dependency

pipelines:
  deploy:
    run: |-
      echo "Hello I am ${devspace.name}" > dependency-deploy.txt
      echo "Hello again I am ${devspace.name}"
  dev:
    run: |-
      echo "Hello I am ${devspace.name}" > dependency-dev.txt
      create_deployments test --set helm.values.containers[0].image=alpine

      start_dev test --set imageSelector=alpine \
                     --set 'command={sleep,999999}' \
                     --set sync[0].path=.:/app
