version: v2beta1
name: dependency

pipelines:
  deploy:
    steps:
    - run: |-
        echo "Hello I am ${devspace.name}" > dependency.txt
  dev:
    steps:
    - run: |-
        create_deployments test --set helm.values.containers[0].image=alpine
        
        start_dev test --set imageSelector=alpine \
                       --set 'command={sleep,999999}' \
                       --set sync[0].path=.:/app
